name: Build AMI after PR is merged

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          touch .env
          echo PGDATABASE=${{ secrets.PGDATABASE }} >> .env
          echo PGUSER=${{ secrets.PGUSER }} >> .env
          echo PGPASSWORD=${{ secrets.PGPASSWORD }} >> .env
          echo PGPORT=${{ secrets.PGPORT }} >> .env
          echo PGHOST=${{ secrets.PGHOST }} >> .env
          echo CSVPATH=$"~/opt/users.csv" >> .env
          echo "cat .env"
          cat .env
          echo "ls -a ."
          ls -a .
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
          
      - name: Packer variables
        run: |
          touch ami.pkrvars.hcl
          echo SOURCE_AMI=\"${{ vars.SOURCE_AMI }}\" >> ami.pkrvars.hcl
          echo INSTANCE_TYPE=\"${{ vars.INSTANCE_TYPE }}\" >> ami.pkrvars.hcl
          echo REGION=\"${{ vars.REGION }}\" >> ami.pkrvars.hcl
          echo PROFILE=\"${{ vars.PROFILE }}\" >> ami.pkrvars.hcl
          echo SSH_USERNAME=\"${{ vars.SSH_USERNAME }}\" >> ami.pkrvars.hcl
          echo AMI_USERS=\"${{ vars.AMI_USERS }}\" >> ami.pkrvars.hcl
          echo OS_NAME=\"${{ vars.OS_NAME }}\" >> ami.pkrvars.hcl
          echo OS_ROOT_TYPE=\"${{ vars.OS_ROOT_TYPE }}\" >> ami.pkrvars.hcl
          echo OS_VER=\"${{ vars.OS_VER }}\" >> ami.pkrvars.hcl

      - name: Run Integration Tests
        run: npm run test:integration
      
      - name: Packer variables
        run: |
          touch ami.pkrvars.hcl
          echo SOURCE_AMI=\"${{ vars.SOURCE_AMI }}\" >> ami.pkrvars.hcl
          echo INSTANCE_TYPE=\"${{ vars.INSTANCE_TYPE }}\" >> ami.pkrvars.hcl
          echo REGION=\"${{ vars.REGION }}\" >> ami.pkrvars.hcl
          echo PROFILE=\"${{ vars.PROFILE }}\" >> ami.pkrvars.hcl
          echo SSH_USERNAME=\"${{ vars.SSH_USERNAME }}\" >> ami.pkrvars.hcl
          echo AMI_USERS=\"${{ vars.AMI_USERS }}\" >> ami.pkrvars.hcl
          echo OS_NAME=\"${{ vars.OS_NAME }}\" >> ami.pkrvars.hcl
          echo OS_ROOT_TYPE=\"${{ vars.OS_ROOT_TYPE }}\" >> ami.pkrvars.hcl
          echo OS_VER=\"${{ vars.OS_VER }}\" >> ami.pkrvars.hcl
        
      - name: Step 2 - zip all the webapp files
        run: |
          zip -r webapp.zip ./
          pwd ./webapp
      - name: Install Packer
        run: |
          PACKER_VERSION="1.9.4"  # specify your desired version
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version
      - name: Initialize Packer
        run: packer init ami.pkr.hcl

      - name: Build AMI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 'packer build --var-file=ami.pkrvars.hcl ami.pkr.hcl'
