name: Integration Tests

on:
  pull_request:
    branches:
      - main # Assuming your primary branch is named 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

        env:
          POSTGRES_DB: ${{ secrets.PGDATABASE }}
          POSTGRES_USER: ${{ secrets.PGUSER }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: "Create env file"
        run: |
          touch .env
          echo PGDATABASE=${{ secrets.PGDATABASE }} >> .env
          cat .env
          echo secrets

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # Assuming you are using Node.js. Change this accordingly.

      - name: Install Dependencies
        run: npm install # chekcout to directory, touch a enc file, pull all secrets

      - name: Run Integration Tests
        run: npm run test:integration # Assuming you have a script in your package.json named "test:integration" that runs your integration tests.
