name: Integration Tests

on:
  pull_request:
    branches:
      - main # Assuming your primary branch is named 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x # Assuming you are using Node.js. Change this accordingly.
      
    - name: Install Dependencies
      run: npm install
      
    - name: Run Integration Tests
      run: npm run test:integration # Assuming you have a script in your package.json named "test:integration" that runs your integration tests.

