name: Packer Validation and Formatting Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Create env file"
        run: |
          touch .env
          echo PGDATABASE=${{ secrets.PGDATABASE }} >> .env
          echo PGUSER=${{ secrets.PGUSER }} >> .env
          echo PGPASSWORD=${{ secrets.PGPASSWORD }} >> .env
          echo PGPORT=${{ secrets.PGPORT }} >> .env
          echo PGHOST=${{ secrets.PGHOST }} >> .env
          echo CSVPATH=$"/opt/users.csv" >> .env
          echo SOURCE_AMI=${{ vars.SOURCE_AMI }} >> .env
          echo INSTANCE_TYPE=${{ vars.INSTANCE_TYPE }}>> .env
          echo REGION=${{ vars.REGION }} >> .env
          echo PROFILE=${{ vars.PROFILE }} >> .env
          echo SSH_USERNAME=${{ vars.SSH_USERNAME }} >> .env
          echo AMI_USERS=${{ vars.AMI_USERS }} >> .env
          echo OS_NAME=${{ vars.OS_NAME }} >> .env
          echo OS_ROOT_TYPE=${{ vars.OS_ROOT_TYPE }} >> .env
          echo OS_VER=${{ vars.OS_VER }} >> .env
          echo "cat .env"
          cat .env
          echo "ls -a ."
          ls -a .
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}

      - name: Packer variables
        run: |
          touch ami.pkrvars.hcl
          echo SOURCE_AMI=\"${{ vars.SOURCE_AMI }}\" >> ami.pkrvars.hcl
          echo INSTANCE_TYPE=\"${{ vars.INSTANCE_TYPE }}\" >> ami.pkrvars.hcl
          echo REGION=\"${{ vars.REGION }}\" >> ami.pkrvars.hcl
          echo PROFILE=\"${{ vars.PROFILE }}\" >> ami.pkrvars.hcl
          echo SSH_USERNAME=\"${{ vars.SSH_USERNAME }}\" >> ami.pkrvars.hcl
          echo AMI_USERS=\"${{ vars.AMI_USERS }}\" >> ami.pkrvars.hcl
          echo OS_NAME=\"${{ vars.OS_NAME }}\" >> ami.pkrvars.hcl
          echo OS_ROOT_TYPE=\"${{ vars.OS_ROOT_TYPE }}\" >> ami.pkrvars.hcl
          echo OS_VER=\"${{ vars.OS_VER }}\" >> ami.pkrvars.hcl
      - name: Step 2 - zip all the webapp files
        run: |
          zip -r webapp.zip ./
          pwd ./webapp
      - name: Install Packer
        run: |
          PACKER_VERSION="1.9.4"  # specify your desired version
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo mv packer /usr/local/bin/
          packer --version
      - name: Initialize Packer
        run: packer init ami.pkr.hcl

      - name: Validate Packer Template
        run: 'packer validate -evaluate-datasources --var-file=ami.pkrvars.hcl ami.pkr.hcl'

      - name: Check Packer Template Formatting
        run: |
          if ! packer fmt -check ami.pkr.hcl; then
            echo "Packer template is not formatted correctly. Please format using 'packer fmt ami.pkr.hcl' and re-push."
            exit 1
          fi
